### ISSUE TITLE
Remaining items todo before full release

### ISSUE THREAD

**Issue by WestDiscGolf** [WestDiscGolf/Fitbit.Net-Webhook#1]
**Update** - It has been [announced](https://github.com/aspnet/WebHooks/issues/296) that the asp.net core webhooks have been moved off the asp.net core 2.1 train and will be in a later release (I'd guess/hope this will be 2.2). I will be continuing with this little side project while this is in transition.

---

The below is the evolving list of items I want to achieve before a "full" or none preview release is generated.

- [ ]  [Improved Logging](https://github.com/WestDiscGolf/Fitbit.Net-Webhook/issues/2) - There is not enough logging in the Package specific classes. Especially around the items the Fitbit API Development portal strongly suggests there are

- [x]  [Return 204](https://github.com/WestDiscGolf/Fitbit.Net-Webhook/issues/3) - The webhook should return 204 on all successful responses. I want to make this as an additional filter in the pipeline and only add in the `OnResourceExecuted` checking the context result

- [ ] [Doc Comments](https://github.com/WestDiscGolf/Fitbit.Net-Webhook/issues/5) - More doc comments need adding

- [ ] [Tests](https://github.com/WestDiscGolf/Fitbit.Net-Webhook/issues/4) - There are not enough unit tests and this needs to be remedied. Also need to look into the new integration test functionality of running an in memory web server which is coming with 2.1.
